openapi: 3.0.3
info:
    title: Locally Imagined backend
    description: Serves all frontend requests
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for locallyimagined
paths:
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginLoginResponseBody'
                            example:
                                jwt: Quisquam eveniet.
                                userID: Dolore et ad voluptatum est at.
            security:
                - login_header_Authorization: []
    /posts/artistposts/{page}:
        get:
            tags:
                - postings
            summary: get_artist_post_page postings
            operationId: postings#get_artist_post_page
            parameters:
                - name: userID
                  in: query
                  description: User ID to get posts for
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: User ID to get posts for
                    example: Qui dolor impedit voluptatem odit.
                  example: Id sint et soluta minus consequatur.
                - name: page
                  in: path
                  description: Page to get posts for
                  required: true
                  schema:
                    type: integer
                    description: Page to get posts for
                    example: 2939887190436290976
                    format: int64
                  example: 1757116098216988445
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/PostResponse'
                                example:
                                    - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                      description: Adipisci ipsam quae repellat sit recusandae maxime.
                                      imageIDs:
                                        - Ab id earum commodi repudiandae voluptatum atque.
                                        - Consequatur rerum ducimus.
                                        - Perspiciatis non aut.
                                      medium: A sunt reiciendis.
                                      postID: Ea nam quibusdam sunt.
                                      price: Magni id cumque.
                                      sold: true
                                      title: In veniam quia officia a.
                                      uploadDate: Labore quisquam reiciendis in.
                                      userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                      username: Accusantium voluptatem quia qui dolorem.
                                    - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                      description: Adipisci ipsam quae repellat sit recusandae maxime.
                                      imageIDs:
                                        - Ab id earum commodi repudiandae voluptatum atque.
                                        - Consequatur rerum ducimus.
                                        - Perspiciatis non aut.
                                      medium: A sunt reiciendis.
                                      postID: Ea nam quibusdam sunt.
                                      price: Magni id cumque.
                                      sold: true
                                      title: In veniam quia officia a.
                                      uploadDate: Labore quisquam reiciendis in.
                                      userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                      username: Accusantium voluptatem quia qui dolorem.
                                    - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                      description: Adipisci ipsam quae repellat sit recusandae maxime.
                                      imageIDs:
                                        - Ab id earum commodi repudiandae voluptatum atque.
                                        - Consequatur rerum ducimus.
                                        - Perspiciatis non aut.
                                      medium: A sunt reiciendis.
                                      postID: Ea nam quibusdam sunt.
                                      price: Magni id cumque.
                                      sold: true
                                      title: In veniam quia officia a.
                                      uploadDate: Labore quisquam reiciendis in.
                                      userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                      username: Accusantium voluptatem quia qui dolorem.
                            example:
                                - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                  description: Adipisci ipsam quae repellat sit recusandae maxime.
                                  imageIDs:
                                    - Ab id earum commodi repudiandae voluptatum atque.
                                    - Consequatur rerum ducimus.
                                    - Perspiciatis non aut.
                                  medium: A sunt reiciendis.
                                  postID: Ea nam quibusdam sunt.
                                  price: Magni id cumque.
                                  sold: true
                                  title: In veniam quia officia a.
                                  uploadDate: Labore quisquam reiciendis in.
                                  userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                  username: Accusantium voluptatem quia qui dolorem.
                                - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                  description: Adipisci ipsam quae repellat sit recusandae maxime.
                                  imageIDs:
                                    - Ab id earum commodi repudiandae voluptatum atque.
                                    - Consequatur rerum ducimus.
                                    - Perspiciatis non aut.
                                  medium: A sunt reiciendis.
                                  postID: Ea nam quibusdam sunt.
                                  price: Magni id cumque.
                                  sold: true
                                  title: In veniam quia officia a.
                                  uploadDate: Labore quisquam reiciendis in.
                                  userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                  username: Accusantium voluptatem quia qui dolorem.
    /posts/create:
        post:
            tags:
                - postings
            summary: create_post postings
            operationId: postings#create_post
            requestBody:
                description: Post info
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Post'
                        example:
                            content:
                                - Consequatur velit eum et.
                                - Repudiandae minus aut.
                            deliverytype: Exercitationem eaque dolores ea.
                            description: Dolor porro assumenda dolor ex.
                            medium: Et rerum.
                            price: Dicta rerum.
                            title: Voluptatem maiores est maiores.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PostingscreatePostResponseBody'
                            example:
                                deliverytype: Ratione voluptas consectetur.
                                description: Similique sed rem quos.
                                imageIDs:
                                    - Sint possimus et aut quidem eaque.
                                    - Expedita numquam natus et nemo aperiam rerum.
                                medium: Soluta est adipisci quia.
                                postID: Qui assumenda quas non.
                                price: Dignissimos voluptatibus dolor ex veniam voluptatibus et.
                                sold: false
                                title: Et est fugiat.
                                uploadDate: Veritatis quod est officiis quidem iure et.
                                userID: Excepturi molestiae.
                                username: Cumque ipsam unde excepturi.
            security:
                - jwt_header_Authorization: []
    /posts/delete/{postID}:
        delete:
            tags:
                - postings
            summary: delete_post postings
            operationId: postings#delete_post
            parameters:
                - name: postID
                  in: path
                  description: Post to delete
                  required: true
                  schema:
                    type: string
                    description: Post to delete
                    example: Libero sunt voluptate dolorem architecto aut sed.
                  example: Maiores qui.
            responses:
                "204":
                    description: No Content response.
            security:
                - jwt_header_Authorization: []
    /posts/edit/{postID}:
        put:
            tags:
                - postings
            summary: edit_post postings
            operationId: postings#edit_post
            parameters:
                - name: title
                  in: query
                  description: Post title
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Post title
                    example: Doloremque magnam labore est fugit facere et.
                  example: Et nihil numquam quae dolore.
                - name: description
                  in: query
                  description: Post description
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Post description
                    example: Aut consequatur consequatur ea similique alias.
                  example: Aliquid non nobis.
                - name: price
                  in: query
                  description: Post price
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Post price
                    example: Ea quas.
                  example: Et ipsum sit dolore non.
                - name: content
                  in: query
                  description: Image content
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Image content
                    example: Repudiandae magni autem.
                  example: Doloremque provident ut culpa sunt quia nostrum.
                - name: medium
                  in: query
                  description: Art type
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Art type
                    example: Repellat porro ea et tempora voluptas.
                  example: Non animi eum quia repudiandae neque sed.
                - name: sold
                  in: query
                  description: is sold
                  allowEmptyValue: true
                  schema:
                    type: boolean
                    description: is sold
                    example: false
                  example: false
                - name: deliverytype
                  in: query
                  description: Delivery type
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Delivery type
                    example: Nihil praesentium id voluptatem animi.
                  example: Iste incidunt.
                - name: imageID
                  in: query
                  description: Image ID
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Image ID
                    example: Ea dolore qui consequatur ut odio non.
                  example: Provident illo tempore enim corrupti ab.
                - name: postID
                  in: path
                  description: Post ID
                  required: true
                  schema:
                    type: string
                    description: Post ID
                    example: Optio consectetur voluptatibus in laudantium.
                  example: Eligendi quia ipsa.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PostResponse'
                            example:
                                deliverytype: Ratione voluptas consectetur.
                                description: Similique sed rem quos.
                                imageIDs:
                                    - Sint possimus et aut quidem eaque.
                                    - Expedita numquam natus et nemo aperiam rerum.
                                medium: Soluta est adipisci quia.
                                postID: Qui assumenda quas non.
                                price: Dignissimos voluptatibus dolor ex veniam voluptatibus et.
                                sold: false
                                title: Et est fugiat.
                                uploadDate: Veritatis quod est officiis quidem iure et.
                                userID: Excepturi molestiae.
                                username: Cumque ipsam unde excepturi.
            security:
                - jwt_header_Authorization: []
    /posts/getimages/{postID}:
        get:
            tags:
                - postings
            summary: get_images_for_post postings
            operationId: postings#get_images_for_post
            parameters:
                - name: postID
                  in: path
                  description: Post to get images for
                  required: true
                  schema:
                    type: string
                    description: Post to get images for
                    example: Tempore ea qui et.
                  example: Et ipsa et.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                                    example: Et cum possimus molestiae fugiat iure.
                                example:
                                    - A error aut molestias ex.
                                    - Doloribus ut.
                                    - Molestias exercitationem est consequatur qui cum ratione.
                            example:
                                - Enim expedita fuga.
                                - Aspernatur et.
    /posts/getpage/{page}:
        get:
            tags:
                - postings
            summary: get_post_page postings
            operationId: postings#get_post_page
            parameters:
                - name: page
                  in: path
                  description: Page to get posts for
                  required: true
                  schema:
                    type: integer
                    description: Page to get posts for
                    example: 6762958111819141091
                    format: int64
                  example: 4519301322116116698
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/PostResponse'
                                example:
                                    - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                      description: Adipisci ipsam quae repellat sit recusandae maxime.
                                      imageIDs:
                                        - Ab id earum commodi repudiandae voluptatum atque.
                                        - Consequatur rerum ducimus.
                                        - Perspiciatis non aut.
                                      medium: A sunt reiciendis.
                                      postID: Ea nam quibusdam sunt.
                                      price: Magni id cumque.
                                      sold: true
                                      title: In veniam quia officia a.
                                      uploadDate: Labore quisquam reiciendis in.
                                      userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                      username: Accusantium voluptatem quia qui dolorem.
                                    - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                      description: Adipisci ipsam quae repellat sit recusandae maxime.
                                      imageIDs:
                                        - Ab id earum commodi repudiandae voluptatum atque.
                                        - Consequatur rerum ducimus.
                                        - Perspiciatis non aut.
                                      medium: A sunt reiciendis.
                                      postID: Ea nam quibusdam sunt.
                                      price: Magni id cumque.
                                      sold: true
                                      title: In veniam quia officia a.
                                      uploadDate: Labore quisquam reiciendis in.
                                      userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                      username: Accusantium voluptatem quia qui dolorem.
                                    - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                      description: Adipisci ipsam quae repellat sit recusandae maxime.
                                      imageIDs:
                                        - Ab id earum commodi repudiandae voluptatum atque.
                                        - Consequatur rerum ducimus.
                                        - Perspiciatis non aut.
                                      medium: A sunt reiciendis.
                                      postID: Ea nam quibusdam sunt.
                                      price: Magni id cumque.
                                      sold: true
                                      title: In veniam quia officia a.
                                      uploadDate: Labore quisquam reiciendis in.
                                      userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                      username: Accusantium voluptatem quia qui dolorem.
                                    - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                      description: Adipisci ipsam quae repellat sit recusandae maxime.
                                      imageIDs:
                                        - Ab id earum commodi repudiandae voluptatum atque.
                                        - Consequatur rerum ducimus.
                                        - Perspiciatis non aut.
                                      medium: A sunt reiciendis.
                                      postID: Ea nam quibusdam sunt.
                                      price: Magni id cumque.
                                      sold: true
                                      title: In veniam quia officia a.
                                      uploadDate: Labore quisquam reiciendis in.
                                      userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                      username: Accusantium voluptatem quia qui dolorem.
                            example:
                                - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                  description: Adipisci ipsam quae repellat sit recusandae maxime.
                                  imageIDs:
                                    - Ab id earum commodi repudiandae voluptatum atque.
                                    - Consequatur rerum ducimus.
                                    - Perspiciatis non aut.
                                  medium: A sunt reiciendis.
                                  postID: Ea nam quibusdam sunt.
                                  price: Magni id cumque.
                                  sold: true
                                  title: In veniam quia officia a.
                                  uploadDate: Labore quisquam reiciendis in.
                                  userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                  username: Accusantium voluptatem quia qui dolorem.
                                - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                  description: Adipisci ipsam quae repellat sit recusandae maxime.
                                  imageIDs:
                                    - Ab id earum commodi repudiandae voluptatum atque.
                                    - Consequatur rerum ducimus.
                                    - Perspiciatis non aut.
                                  medium: A sunt reiciendis.
                                  postID: Ea nam quibusdam sunt.
                                  price: Magni id cumque.
                                  sold: true
                                  title: In veniam quia officia a.
                                  uploadDate: Labore quisquam reiciendis in.
                                  userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                  username: Accusantium voluptatem quia qui dolorem.
                                - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                  description: Adipisci ipsam quae repellat sit recusandae maxime.
                                  imageIDs:
                                    - Ab id earum commodi repudiandae voluptatum atque.
                                    - Consequatur rerum ducimus.
                                    - Perspiciatis non aut.
                                  medium: A sunt reiciendis.
                                  postID: Ea nam quibusdam sunt.
                                  price: Magni id cumque.
                                  sold: true
                                  title: In veniam quia officia a.
                                  uploadDate: Labore quisquam reiciendis in.
                                  userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                  username: Accusantium voluptatem quia qui dolorem.
                                - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                  description: Adipisci ipsam quae repellat sit recusandae maxime.
                                  imageIDs:
                                    - Ab id earum commodi repudiandae voluptatum atque.
                                    - Consequatur rerum ducimus.
                                    - Perspiciatis non aut.
                                  medium: A sunt reiciendis.
                                  postID: Ea nam quibusdam sunt.
                                  price: Magni id cumque.
                                  sold: true
                                  title: In veniam quia officia a.
                                  uploadDate: Labore quisquam reiciendis in.
                                  userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                  username: Accusantium voluptatem quia qui dolorem.
    /posts/getpagefiltered/{page}:
        get:
            tags:
                - postings
            summary: get_post_page_filtered postings
            operationId: postings#get_post_page_filtered
            parameters:
                - name: keyword
                  in: query
                  description: Search bar keyword to search for in title and description
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Search bar keyword to search for in title and description
                    example: Est voluptate error praesentium.
                  example: Vel sit et eveniet dolores.
                - name: startDate
                  in: query
                  description: Filter attribute to see posts after given date
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Filter attribute to see posts after given date
                    example: Non error et cumque rerum repellat sed.
                  example: Quod laborum suscipit commodi.
                - name: endDate
                  in: query
                  description: Filter attribute to see posts before given date
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Filter attribute to see posts before given date
                    example: Explicabo quidem sed.
                  example: Cum accusantium laboriosam esse magnam.
                - name: medium
                  in: query
                  description: Filter attribute to see posts with given medium type
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Filter attribute to see posts with given medium type
                    example: Totam labore id quia culpa delectus.
                  example: Qui atque repudiandae voluptatibus est a numquam.
                - name: page
                  in: path
                  description: Page to get posts for
                  required: true
                  schema:
                    type: integer
                    description: Page to get posts for
                    example: 8694291482644665451
                    format: int64
                  example: 7186844506708638174
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/PostResponse'
                                example:
                                    - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                      description: Adipisci ipsam quae repellat sit recusandae maxime.
                                      imageIDs:
                                        - Ab id earum commodi repudiandae voluptatum atque.
                                        - Consequatur rerum ducimus.
                                        - Perspiciatis non aut.
                                      medium: A sunt reiciendis.
                                      postID: Ea nam quibusdam sunt.
                                      price: Magni id cumque.
                                      sold: true
                                      title: In veniam quia officia a.
                                      uploadDate: Labore quisquam reiciendis in.
                                      userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                      username: Accusantium voluptatem quia qui dolorem.
                                    - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                      description: Adipisci ipsam quae repellat sit recusandae maxime.
                                      imageIDs:
                                        - Ab id earum commodi repudiandae voluptatum atque.
                                        - Consequatur rerum ducimus.
                                        - Perspiciatis non aut.
                                      medium: A sunt reiciendis.
                                      postID: Ea nam quibusdam sunt.
                                      price: Magni id cumque.
                                      sold: true
                                      title: In veniam quia officia a.
                                      uploadDate: Labore quisquam reiciendis in.
                                      userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                      username: Accusantium voluptatem quia qui dolorem.
                                    - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                      description: Adipisci ipsam quae repellat sit recusandae maxime.
                                      imageIDs:
                                        - Ab id earum commodi repudiandae voluptatum atque.
                                        - Consequatur rerum ducimus.
                                        - Perspiciatis non aut.
                                      medium: A sunt reiciendis.
                                      postID: Ea nam quibusdam sunt.
                                      price: Magni id cumque.
                                      sold: true
                                      title: In veniam quia officia a.
                                      uploadDate: Labore quisquam reiciendis in.
                                      userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                      username: Accusantium voluptatem quia qui dolorem.
                                    - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                      description: Adipisci ipsam quae repellat sit recusandae maxime.
                                      imageIDs:
                                        - Ab id earum commodi repudiandae voluptatum atque.
                                        - Consequatur rerum ducimus.
                                        - Perspiciatis non aut.
                                      medium: A sunt reiciendis.
                                      postID: Ea nam quibusdam sunt.
                                      price: Magni id cumque.
                                      sold: true
                                      title: In veniam quia officia a.
                                      uploadDate: Labore quisquam reiciendis in.
                                      userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                      username: Accusantium voluptatem quia qui dolorem.
                            example:
                                - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                  description: Adipisci ipsam quae repellat sit recusandae maxime.
                                  imageIDs:
                                    - Ab id earum commodi repudiandae voluptatum atque.
                                    - Consequatur rerum ducimus.
                                    - Perspiciatis non aut.
                                  medium: A sunt reiciendis.
                                  postID: Ea nam quibusdam sunt.
                                  price: Magni id cumque.
                                  sold: true
                                  title: In veniam quia officia a.
                                  uploadDate: Labore quisquam reiciendis in.
                                  userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                  username: Accusantium voluptatem quia qui dolorem.
                                - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                  description: Adipisci ipsam quae repellat sit recusandae maxime.
                                  imageIDs:
                                    - Ab id earum commodi repudiandae voluptatum atque.
                                    - Consequatur rerum ducimus.
                                    - Perspiciatis non aut.
                                  medium: A sunt reiciendis.
                                  postID: Ea nam quibusdam sunt.
                                  price: Magni id cumque.
                                  sold: true
                                  title: In veniam quia officia a.
                                  uploadDate: Labore quisquam reiciendis in.
                                  userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                  username: Accusantium voluptatem quia qui dolorem.
                                - deliverytype: Voluptatem possimus quo sunt eligendi asperiores.
                                  description: Adipisci ipsam quae repellat sit recusandae maxime.
                                  imageIDs:
                                    - Ab id earum commodi repudiandae voluptatum atque.
                                    - Consequatur rerum ducimus.
                                    - Perspiciatis non aut.
                                  medium: A sunt reiciendis.
                                  postID: Ea nam quibusdam sunt.
                                  price: Magni id cumque.
                                  sold: true
                                  title: In veniam quia officia a.
                                  uploadDate: Labore quisquam reiciendis in.
                                  userID: Laborum distinctio accusamus veniam doloribus ipsum.
                                  username: Accusantium voluptatem quia qui dolorem.
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/User'
                        example:
                            email: Nihil repellendus et ratione.
                            firstName: Autem minima reprehenderit consequuntur.
                            lastName: Veritatis voluptatum nihil.
                            phone: Est iusto eos sunt quis deleniti.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Alias exercitationem debitis aut ut aut accusamus.
                            example: Doloribus blanditiis molestiae quo adipisci aut quibusdam.
            security:
                - signup_header_Authorization: []
    /users/get_contact_info:
        get:
            tags:
                - users
            summary: get_contact_info users
            operationId: users#get_contact_info
            parameters:
                - name: userID
                  in: query
                  description: userid of user whose info to retrieve
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: userid of user whose info to retrieve
                    example: Illum deleniti repellendus dolores minima quod quia.
                  example: Qui ipsam facere.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                            example:
                                email: Qui aut aut saepe eos nam placeat.
                                firstName: Sit voluptates.
                                lastName: Sed nemo rem nisi consequatur.
                                phone: Iure quam possimus quaerat maxime et.
    /users/update_bio:
        post:
            tags:
                - users
            summary: update_bio users
            operationId: users#update_bio
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateBioRequestBody'
                        example:
                            bio: Eaque assumenda voluptatem et commodi atque earum.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                            example:
                                email: Qui aut aut saepe eos nam placeat.
                                firstName: Sit voluptates.
                                lastName: Sed nemo rem nisi consequatur.
                                phone: Iure quam possimus quaerat maxime et.
            security:
                - jwt_header_Authorization: []
components:
    schemas:
        LoginLoginResponseBody:
            $ref: '#/components/schemas/LoginResponse'
        LoginResponse:
            type: object
            properties:
                jwt:
                    type: string
                    description: jwt used for future authentication
                    example: Qui et.
                userID:
                    type: string
                    description: users ID
                    example: Et quos non est dolor nobis.
            description: Response from logging in
            example:
                jwt: Aut inventore dicta.
                userID: Quis aliquid sequi nesciunt repellendus alias id.
        Post:
            type: object
            properties:
                content:
                    type: array
                    items:
                        type: string
                        example: Adipisci porro.
                    description: Post content
                    example:
                        - Autem dolorem animi.
                        - Doloremque et accusantium.
                deliverytype:
                    type: string
                    description: Delivery type
                    example: Saepe recusandae quos.
                description:
                    type: string
                    description: Post description
                    example: Qui aliquid id amet nesciunt veniam.
                medium:
                    type: string
                    description: Art type
                    example: Veritatis doloribus modi maxime aut.
                price:
                    type: string
                    description: Post price
                    example: Necessitatibus ut natus.
                title:
                    type: string
                    description: Post title
                    example: Adipisci delectus et ducimus.
            description: Describes a post payload
            example:
                content:
                    - Expedita rerum.
                    - Et molestiae voluptatum accusantium.
                    - Voluptas facilis.
                deliverytype: Nesciunt quod et error.
                description: Odit voluptas non quo id odit.
                medium: Maxime excepturi nisi alias qui.
                price: Qui natus pariatur.
                title: Cum animi error deleniti esse.
            required:
                - title
                - description
                - price
                - content
                - medium
                - deliverytype
        PostResponse:
            type: object
            properties:
                deliverytype:
                    type: string
                    description: Delivery type
                    example: Et rerum laboriosam qui quas.
                description:
                    type: string
                    description: Post description
                    example: Sequi impedit consequatur in laudantium.
                imageIDs:
                    type: array
                    items:
                        type: string
                        example: Sit sed consectetur minima recusandae veritatis eos.
                    description: Image ID
                    example:
                        - Sunt dolor ipsa doloribus.
                        - Quos ducimus voluptates magnam quasi.
                        - Aspernatur vitae est praesentium et quos voluptatem.
                        - Repellendus blanditiis aliquid dolorem ipsum et rerum.
                medium:
                    type: string
                    description: Art type
                    example: Sint rerum officiis qui odit distinctio quaerat.
                postID:
                    type: string
                    description: Post ID
                    example: Impedit doloribus quidem.
                price:
                    type: string
                    description: Post price
                    example: Laboriosam excepturi iure quam et dolorem aspernatur.
                sold:
                    type: boolean
                    description: is sold
                    example: true
                title:
                    type: string
                    description: Post title
                    example: Ut occaecati facere.
                uploadDate:
                    type: string
                    description: Upload Date
                    example: Vitae dolor.
                userID:
                    type: string
                    description: User id associated with post
                    example: Repellat rerum quasi et sit.
                username:
                    type: string
                    description: Username associated with post
                    example: Voluptatibus eaque vel omnis.
            description: Describes a post response
            example:
                deliverytype: Ducimus doloribus et.
                description: Distinctio eos nulla eos.
                imageIDs:
                    - Placeat aut.
                    - Dolor autem sit aut ab.
                    - Quasi eaque fugit sed.
                    - Et placeat provident.
                medium: Id soluta autem non.
                postID: Alias ex ea natus.
                price: Totam odit non provident officiis ea.
                sold: false
                title: Totam doloremque dolore et.
                uploadDate: Tempore nam aspernatur totam incidunt.
                userID: Quas adipisci id aliquid sit molestiae minima.
                username: Nulla quos repudiandae dolores.
            required:
                - title
                - description
                - price
                - imageIDs
                - postID
                - medium
                - uploadDate
                - sold
                - deliverytype
                - username
                - userID
        PostingscreatePostResponseBody:
            $ref: '#/components/schemas/PostResponse'
        UpdateBioRequestBody:
            type: object
            properties:
                bio:
                    type: string
                    description: New bio to be addeed
                    example: Labore sint ad possimus error omnis voluptas.
            example:
                bio: Id consequatur hic enim assumenda.
            required:
                - bio
        User:
            type: object
            properties:
                email:
                    type: string
                    description: Email
                    example: Quaerat suscipit qui corrupti facere dolorem quod.
                firstName:
                    type: string
                    description: First name
                    example: Inventore eum ut incidunt sunt delectus est.
                lastName:
                    type: string
                    description: Last name
                    example: Non adipisci non nostrum iure qui omnis.
                phone:
                    type: string
                    description: Phone number
                    example: Et et inventore officia.
            description: Describes a user
            example:
                email: Porro omnis dolorem reiciendis quidem deserunt qui.
                firstName: Quos incidunt.
                lastName: Voluptatem labore magni non qui.
                phone: Qui est soluta.
            required:
                - firstName
                - lastName
                - phone
                - email
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token retrieved via the login endpoint.
            scheme: bearer
        login_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during login
            scheme: basic
        signup_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signup
            scheme: basic
tags:
    - name: login
    - name: signup
    - name: users
    - name: postings
